import Providers from "@/lib/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { useRouter } from "next/navigation";
import HeaderSection from "@/components/ui/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          style={{
            margin: 0,
            padding: 0,
          }}
          className={inter.className}
        >
          <HeaderSection />
          {children}
          <Toaster position="top-right" reverseOrder={false} />
        </body>
      </html>
    </Providers>
  );
}
